apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: argocd
spec:
  type: ClusterIP
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80