apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  namespace: argocd
spec:
  replicas: 4
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: josephadewole1/fastapi:latest
        resources:
          requests:
            cpu: 200m
            memory: 100Mi
        ports:
        - containerPort: 80
        env:
          - name: REDIS_HOST
            value: "redis-service"   # Redis Service name for DNS resolution
          - name: REDIS_PORT
            value: "6379"